databases:
  - name: expenser-db
    plan: free
    databaseName: expenser
    user: expenser_user

services:
  - type: web
    name: expenser-app
    runtime: docker
    plan: free
    envVars:
      - key: DB_URL
        fromDatabase:
          name: expenser-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_KEY
        generate: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
